"""Senado Federal — Dados Abertos ``/processo`` service.

Verified live on 2026-09-23:

* ``GET https://legis.senado.leg.br/dadosabertos/processo?sigla=PL&numero=278&ano=2026``
  returns a JSON array of objects with fields ``id, identificacao ("PL 278/2026"),
  codigoMateria, ementa, dataApresentacao, situacaoAtual, dataSituacaoAtual,
  tramitando, urlDocumento (full-text PDF via sdleg-getter), tipoDocumento,
  tipoConteudo, autoria, casaIdentificadora, objetivo, ultimaInformacaoAtualizada,
  dataUltimaAtualizacao``.
* The OpenAPI spec (``/dadosabertos/v3/api-docs``) lists ``termo`` (free-text),
  ``dataInicioApresentacao``/``dataFimApresentacao``, ``tramitando`` (S/N),
  ``tipoNorma``/``numeroNorma``/``anoNorma`` (the norm generated by the
  process) and ``numdias`` (updated in the last N days, max 30).
* The legacy ``/materia/pesquisa/lista?palavraChave=`` endpoint returns an
  empty ``PesquisaBasicaMateria`` with ``DataDesativacaoCompleta: 2026-02-01``.
  Anything built on it (older R/Python packages) silently returns nothing.

Edge cases handled here:

* A live probe of ``?sigla=PL&ano=2026&tramitando=S`` returned exactly 100
  rows, which looks like a hard page cap. When a response has >= 100 rows
  the sweep splits the date window by year and warns if a yearly window is
  still at the cap.
* ``identificacao`` is parsed with ``parse_identificacao``; rows without a
  parseable identifier are kept with ``doc_type="processo"`` so nothing is
  silently dropped.
* ``norm_lookup`` resolves the process that generated a given norm
  (Lei 15.504/2026 -> PL 278/2026) and emits an ``ENACTED_AS`` relation.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from ..models import (
    ConnectorResult,
    Document,
    Layer,
    Relation,
    RelationType,
    Status,
    build_urn,
    normalize_type,
    parse_identificacao,
)
from ..terms import match_terms
from . import Context

BASE = "https://legis.senado.leg.br/dadosabertos"
PAGE_CAP = 100  # observed, not documented

SITUACAO_TO_STATUS = {
    "transformad": Status.ENACTED,  # "TRANSFORMADA EM NORMA JURÍDICA"
    "aprovada a materia": Status.PROPOSED,
    "arquivad": Status.ARCHIVED,
    "prejudicad": Status.ARCHIVED,
    "retirad": Status.ARCHIVED,
    "perda de eficacia": Status.LAPSED,
    "encerrada a vigencia": Status.LAPSED,
    "vetad": Status.REVOKED,
}


def _status(situacao: str | None, tramitando: str | None) -> Status:
    norm = normalize_type(situacao or "")
    for needle, status in SITUACAO_TO_STATUS.items():
        if needle in norm:
            return status
    if (tramitando or "").upper() == "N" and norm:
        return Status.ARCHIVED  # ended without a recognised terminal state
    return Status.PROPOSED


def document_from_item(item: dict[str, Any]) -> Document:
    ident = parse_identificacao(item.get("identificacao") or "")
    if ident:
        sigla, numero, ano = ident
    else:
        sigla, numero, ano = "processo", "", None
        apres = item.get("dataApresentacao") or ""
        if apres[:4].isdigit():
            ano = int(apres[:4])
    ementa = item.get("ementa") or ""
    matched, strength = match_terms(ementa, item.get("objetivo") or "")
    proc_id = item.get("id")
    cod_materia = item.get("codigoMateria")
    return Document(
        source="senado",
        layer=Layer.FEDERAL_BILL,
        jurisdiction="BR",
        doc_type=sigla.lower(),
        number=numero,
        year=ano,
        title=item.get("identificacao") or f"processo {proc_id}",
        ementa=ementa,
        issuer="Senado Federal",
        house=(item.get("casaIdentificadora") or "SF").upper(),
        date=(item.get("dataApresentacao") or "")[:10] or None,
        url=f"https://www25.senado.leg.br/web/atividade/materias/-/materia/{cod_materia}" if cod_materia else "",
        text_url=item.get("urlDocumento") or "",
        status=_status(item.get("situacaoAtual"), item.get("tramitando")),
        matched_terms=matched,
        match_strength=strength,
        extra={
            "senado_id": proc_id,
            "codigo_materia": cod_materia,
            "situacao": item.get("situacaoAtual"),
            "data_situacao": item.get("dataSituacaoAtual"),
            "tramitando": item.get("tramitando"),
            "tipo_documento": item.get("tipoDocumento"),
            "autoria": item.get("autoria"),
            "ultima_atualizacao": item.get("dataUltimaAtualizacao"),
        },
    )


def _get(ctx: Context, res: ConnectorResult, params: dict[str, Any]) -> tuple[list[dict[str, Any]] | None, int, str]:
    """One GET /processo -> (rows or None, http status, error detail).

    Callers decide what to log: the request-shape ladder treats a 400 as
    "try the next shape", everything else is an error.
    """
    r = ctx.fetcher.get(f"{BASE}/processo", params=params, headers={"Accept": "application/json"})
    res.requests_made += 1
    if not r.ok:
        return None, r.status, ("" if r.error == "dry_run" else r.error_detail())
    try:
        payload = r.json()
    except ValueError as exc:
        return None, r.status, f"invalid JSON ({exc})"
    if payload is None:
        return [], r.status, ""
    if isinstance(payload, dict):  # defensive: some services wrap arrays
        for key in ("processos", "dados", "items"):
            if isinstance(payload.get(key), list):
                return payload[key], r.status, ""
        return [], r.status, ""
    return (payload if isinstance(payload, list) else []), r.status, ""


def _year_windows(since: dt.date, until: dt.date) -> list[tuple[dt.date, dt.date]]:
    windows = []
    year = since.year
    while year <= until.year:
        start = max(since, dt.date(year, 1, 1))
        end = min(until, dt.date(year, 12, 31))
        windows.append((start, end))
        year += 1
    return windows


def _in_window(row: dict[str, Any], since: dt.date, until: dt.date) -> bool:
    raw = (row.get("dataApresentacao") or "")[:10]
    try:
        when = dt.date.fromisoformat(raw)
    except ValueError:
        return True
    return since <= when <= until


def request_shapes(term: str, since: dt.date, until: dt.date) -> list[tuple[str, list[dict[str, Any]], bool]]:
    """Request shapes for a ``termo`` search, tried in order until one is
    accepted. Each entry: (name, list of param dicts to union, client-side
    date filter needed?).

    Verified live 2026-09-23: ``sigla+numero+ano``, ``sigla+ano+tramitando``
    and ``tipoNorma+numeroNorma+anoNorma``. The first live run (2026-09-24)
    got HTTP 400 for ``termo + dataInicioApresentacao + dataFimApresentacao``
    over 2024-01-01..2026-09-24, so ``termo + ano`` (per year) is the second
    shape: ``ano`` is known to be accepted.
    """
    return [
        ("termo_window", [{"termo": term, "dataInicioApresentacao": since.isoformat(), "dataFimApresentacao": until.isoformat()}], False),
        ("termo_per_year", [{"termo": term, "ano": y} for y in range(since.year, until.year + 1)], True),
        ("termo_start_only", [{"termo": term, "dataInicioApresentacao": since.isoformat()}], True),
        ("termo_only", [{"termo": term}], True),
    ]


def search_term(ctx: Context, res: ConnectorResult, term: str) -> list[dict[str, Any]]:
    """Search ``termo`` over the date range, degrading through request shapes
    on HTTP 400 and splitting by year when the page cap is hit."""
    rejected: list[str] = []
    for name, param_sets, client_filter in request_shapes(term, ctx.since, ctx.until):
        collected: list[dict[str, Any]] = []
        failed = False
        for params in param_sets:
            rows, status, detail = _get(ctx, res, params)
            if rows is None:
                if status == 0 and ctx.fetcher.dry_run:
                    return []
                if status == 400:
                    rejected.append(f"{name} {params}: {detail}")
                else:
                    res.errors.append(f"/processo {params}: {detail or f'HTTP {status}'}")
                failed = True
                break
            if len(rows) >= PAGE_CAP and "ano" not in params:
                res.notes.append(f"termo={term!r} {name}: {len(rows)} rows (>= cap {PAGE_CAP}); splitting by year")
                rows = []
                for start, end in _year_windows(ctx.since, ctx.until):
                    sub, s_status, s_detail = _get(ctx, res, {"termo": term, "ano": start.year})
                    if sub is None:
                        res.errors.append(f"/processo termo={term!r} ano={start.year}: {s_detail or f'HTTP {s_status}'}")
                        continue
                    if len(sub) >= PAGE_CAP:
                        res.notes.append(f"termo={term!r} {start.year}: still {len(sub)} rows at cap; results may be truncated")
                    rows.extend(sub)
            elif len(rows) >= PAGE_CAP:
                res.notes.append(f"termo={term!r} {params}: {len(rows)} rows at cap; results may be truncated")
            collected.extend(rows)
        if failed:
            continue
        if rejected:
            res.notes.append(f"termo={term!r}: shape '{name}' accepted after rejections: " + " | ".join(rejected))
        if client_filter:
            collected = [r for r in collected if _in_window(r, ctx.since, ctx.until)]
        return collected
    res.errors.append(f"termo={term!r}: every request shape rejected — " + " | ".join(rejected))
    return []


def norm_lookup(ctx: Context, res: ConnectorResult, tipo_norma: str, numero: str, ano: int) -> list[dict[str, Any]]:
    """Processes that generated a given norm (e.g. LEI 15504/2026)."""
    rows, status, detail = _get(ctx, res, {"tipoNorma": tipo_norma.upper(), "numeroNorma": numero, "anoNorma": ano})
    if rows is None:
        if detail:
            res.errors.append(f"/processo tipoNorma={tipo_norma} numeroNorma={numero} anoNorma={ano}: {detail}")
        return []
    return rows


def sweep(ctx: Context) -> ConnectorResult:
    res = ConnectorResult(name="senado")
    seen: dict[Any, dict[str, Any]] = {}
    for term in ctx.query_terms:
        for row in search_term(ctx, res, term):
            key = row.get("id") or row.get("codigoMateria") or row.get("identificacao")
            if key is not None and key not in seen:
                seen[key] = row
    for row in seen.values():
        doc = document_from_item(row)
        if doc.match_strength == "none":
            res.notes.append(f"near-miss: {doc.title}")
            continue
        res.documents.append(doc)

    # Norm -> process linkage for norms the caller cares about (config).
    for norm in ctx.config.get("senado_norm_lookups", []):
        try:
            tipo, numero, ano = norm["tipo"], str(norm["numero"]), int(norm["ano"])
        except (KeyError, TypeError, ValueError):
            res.errors.append(f"bad senado_norm_lookups entry: {norm!r}")
            continue
        for row in norm_lookup(ctx, res, tipo, numero, ano):
            doc = document_from_item(row)
            doc.status = Status.ENACTED if doc.status == Status.PROPOSED else doc.status
            if doc.key not in {d.key for d in res.documents}:
                res.documents.append(doc)
            urn = build_urn(tipo, numero, ano)
            if urn:
                res.relations.append(
                    Relation(src=doc.key, dst=urn, type=RelationType.ENACTED_AS,
                             evidence=f"senado /processo tipoNorma={tipo} numeroNorma={numero} anoNorma={ano}",
                             source="senado")
                )
    res.notes.append(f"unique processos from API: {len(seen)}; kept after term rule: {len(res.documents)}")
    return res
